# Generates development image using Alpine base

FROM thevlang/vlang:alpine-build

LABEL org.opencontainers.image.authors="helto4real <helto4real@joysoftware.xyz>, Sandro Martini <sandro.martini@gmail.com>"

# TODO: check if change to a source folder ... wip
WORKDIR /opt/vlang

RUN git clone --depth 1 https://github.com/vlang/v /opt/vlang && \
    make VFLAGS='-cc gcc' && v -version && \
    mkdir /src

WORKDIR /src
