# Generates development image using Alpine base

FROM thevlang/vlang:alpine-build

LABEL org.opencontainers.image.authors="helto4real <helto4real@joysoftware.xyz>, Sandro Martini <sandro.martini@gmail.com>"

WORKDIR /opt/vlang

# TODO: check if clone only last commit ... wip
RUN git clone https://github.com/vlang/v /opt/vlang && \
    make VFLAGS='-cc gcc' && v -version && \
    mkdir /src

WORKDIR /src
