# Generates basic image with compiled V using tcc
FROM thevlang/vlang:ubuntu-build

LABEL org.opencontainers.image.authors="helto4real <helto4real@joysoftware.xyz>, Sandro Martini <sandro.martini@gmail.com>"

WORKDIR /opt/vlang

RUN git clone https://github.com/vlang/v /opt/vlang && \ 
    make CC=clang && v -version && \
    mkdir /src
