# Generates development image based on Alpine, with V compiled using clang
FROM thevlang/vlang:alpine-build

LABEL org.opencontainers.image.authors="helto4real <helto4real@joysoftware.xyz>, Sandro Martini <sandro.martini@gmail.com>"

WORKDIR /opt/vlang

RUN git clone --depth 1 https://github.com/vlang/v /opt/vlang && \
    make VFLAGS='-cc gcc' && v -version && \
    mkdir /src

WORKDIR /src
