# Generates basic image with compiled V using tcc
FROM thevlang/vlang:ubuntu-build

LABEL org.opencontainers.image.authors="helto4real <helto4real@joysoftware.xyz>, Sandro Martini <sandro.martini@gmail.com>"

# TODO: check if change to a source folder ... wip
WORKDIR /opt/vlang

# TODO: install even dependencies (and related tools) for WASM ... wip

RUN git clone --depth 1 https://github.com/vlang/v /opt/vlang && \ 
    make CC=clang && v -version && \
    mkdir /src
